import io
import zipfile
from fastapi import APIRouter, Response
from schemas.api_schemas import StarterKitConfigSchema

router = APIRouter(prefix="/starter-kit", tags=["Starter Kit Generator"])

@router.post("/download")
async def download_starter_kit(cfg: StarterKitConfigSchema):
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as z:
        # README.md
        readme = f"""# {cfg.name} (Generated by APIVerse)
Stack: {cfg.stack.upper()}
Selected APIs: {', '.join(cfg.selected_apis)}

## Getting Started
1. Copy `.env.example` to `.env.local`
2. Run `pnpm install` or `npm install`
3. Start the dev server: `pnpm dev`
"""
        z.writestr("README.md", readme)
        
        # .env.example
        env_vars = ["# APIVerse Autonomous Environment Config\nPORT=3000\n"]
        for api in cfg.selected_apis:
            env_vars.append(f"{api.upper()}_API_KEY=your_{api.lower()}_key_here\n")
        z.writestr(".env.example", "".join(env_vars))
        
        # Dockerfile
        if cfg.include_docker:
            z.writestr("Dockerfile", """FROM node:18-alpine AS runner
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
""")

        # index.ts / server.ts
        z.writestr("src/index.ts", """// Generated APIVerse Starter Client
console.log("APIVerse starter kit booted successfully.");
""")

    zip_buffer.seek(0)
    return Response(
        content=zip_buffer.getvalue(),
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename={cfg.name.lower().replace(' ', '_')}_starter.zip"}
    )
